### ISSUE TITLE
Dockerfile for Qristal: can the CI Token and the use of the private GitLab repository be avoided?

### ISSUE THREAD

**Issue by rsoftone** [qbrilliance/qristal#3]
_[This question is raised on behalf of participants at the monthly Qristal Community Developers meetup]_

When a community developer is using `docker/Dockerfile` they run into the requirement for providing $GIT_TOKEN (a GitLab private repository access Token): (lines 28 - 34)

```dockerfile
RUN git clone https://gitlab-ci-token:${GIT_TOKEN}@gitlab.com/qbau/software-and-apps/QBSDK.git qristal \
    && cd qristal \
    && git fetch origin \
    && git checkout ${QBSDK_TAG} \
    && cmake -S . -B build --preset $QBSDK_PRESET -DCORE_TAG=${CORE_TAG} -DDECODER_TAG=${DECODER_TAG} -DINTEGRATIONS_TAG=${INTEGRATIONS_TAG} -DINSTALL_MISSING=ON -DCMAKE_BUILD_TYPE=None -DWARNINGS=OFF -DWITH_TKET=ON -DTKET_DIR=${QB_DIR}/tket-local -DCMAKE_INSTALL_PREFIX=${QB_DIR}/qristal \
    && cmake --build build -- -j$(nproc) \
    && cmake --install build 
``` 

Is it possible to instead clone from the publicly available repository: https://github.com/qbrilliance/qristal and thereby avoid needing access tokens from GitLab CI?

**Comment by patscott** [comment]
The answer is yes, but a more appropriate response to this question would be "if you're curious, just try it!"

Note however that rebuilding the Docker image is not actually an intended user workflow, as the image is already built and publicly available at registry.gitlab.com/qbau/software-and-apps/public/qbsdk/qristal-sdk (see https://gitlab.com/qbau/software-and-apps/public/QBSDK/container_registry/5591735 for a web overview).  The Dockerfile is just there for our own CI/CD convenience, like things such as the .gitlab-ci.yml file.  It might be removed in a future version of the code.
